---
title: "Publications"
format: html
---

## NeuroCognitive Translations Lab

### [Methamphetamine‐related working memory difficulties underpinned by reduced frontoparietal responses](https://doi.org/10.1111/adb.13444)

Working memory difficulties are common, debilitating, and may pose barriers to recovery for people who use methamphetamine. Yet, little is known regarding the neural dysfunctions accompanying these difficulties. Here, we acquired cross-sectional, functional magnetic resonance imaging while people with problematic methamphetamine-use experience (MA+, n = 65) and people without methamphetamine-use experience (MA−, n = 44) performed a parametric n-back task (0-back through 2-back). Performance on tasks administered outside of the scanner, together with n-back performance, afforded to determine a latent dimension of participants' working memory ability. Behavioural results indicated that MA+ participants exhibited lower scores on this dimension compared to MA− participants (d = −1.39, p \< .001). Whole-brain imaging results also revealed that MA+ participants exhibited alterations in load-induced responses predominantly in frontoparietal and default-mode areas. Specifically, while the MA− group exhibited monotonic activation increases within frontoparietal areas and monotonic decreases within default-mode areas from 0-back to 2-back, MA+ participants showed a relative attenuation of these load-induced activation patterns (d = −1.55, p \< .001). Moreover, increased activations in frontoparietal areas from 0- to 2-back were related to greater working memory ability among MA+ participants (r = .560, p = .004). No such effects were observed for default-mode areas. In sum, reductions in working memory ability were observed alongside load-induced dysfunctions in frontoparietal and default-mode areas for people with problematic methamphetamine-use experience. Among them, load-induced activations within frontoparietal areas were found to have a strong and specific relationship to individual differences in working memory ability, indicating a putative neural signature of the working memory difficulties associated with chronic methamphetamine use.

Citation: Roy, R. J., Parvaz, M. A., Wakabayashi, K. T., Blair, R. J., & Hubbard, N. A. (2024). Methamphetamine‐related working memory difficulties underpinned by reduced frontoparietal responses. Addiction Biology, 29(10). https://doi.org/10.1111/adb.13444

## Early Psychosis Intervention Clinic

### [Reducing Duration of Untreated Psychosis: Strengthening the Case for Early Detection Campaigns](http://dx.doi.org/10.1176/appi.ps.20240061)

Objective: The Clear Answers to Louisiana Mental Health (CALM) campaign’s objective is to reduce the duration of untreated psychosis (DUP) of patients experiencing first-episode psychosis in the New Orleans community. Methods: CALM used mass transit and digital marketing and local community engagement strategies to reduce DUP in referrals to the Early Psychosis Intervention Clinic–New Orleans. DUP measures were collected for clinic referrals pre- and post-CALM launch (N=116). Analytics from marketing strategies were used to evaluate campaign success. Results: In the first 12 months of CALM, the mean DUP from onset of psychotic symptoms to clinic entry decreased from a median of 6.6 (interquartile range \[IQR\]=2.5–14.9) to 2.1 (IQR=1.1–10.7) months. Time from onset of psychotic symptoms to first antipsychotic treatment decreased from a median of 2.0 (IQR=0.5–8.6) to 0.2 (IQR=0.0–0.7) months. Conclusions: The CALM campaign produced promising results for reducing DUP in referrals to a coordinated specialty care program.

Citation: Weiss, A., Chaudhry, S., Atiya, W., Long, S., Roy, R., & Mojtabai, R. (2025). Reducing Duration of Untreated Psychosis: Strengthening the Case for Early Detection Campaigns. Psychiatric Services, 76(6), 598–601. https://doi.org/10.1176/appi.ps.20240061

### [Psychosis, Telehealth, and COVID-19: Engagement and Hospitalization Pre- and Peri-Pandemic](https://doi.org/10.1017/dmp.2023.144)

Telehealth has become the linchpin of virtual care since the coronavirus disease 2019 (COVID-19) pandemic. Research has shown the use of telehealth has improved patient engagement, medication adherence, and satisfaction. Psychiatry is poised to benefit from telehealth because individual psychotherapy and parts of medication management can be done virtually. However, some practitioners believe telehealth interferes with rapport building, detection of nonverbal ques, continuity of care, and collection of physiological data. This is a particular issue for coordinated specialty care (CSC), an evidence-based practice that relies on multiple specialties and high levels of patient engagement to improve outcomes in patients with first-episode psychosis (FEP). This study extracted data from medical records stretching across four years to compare treatments outcomes in relation to the type of care (virtual, hybrid, or in-person) the patient received. Engagement at EPIC-NOLA spiked in 2020 and stabilized in 2021 and 2022. Underlying these trends is the inclusion of telehealth and hybrid care (receiving care both in-person and by means of telehealth) as a treatment model. While this study cannot assign cause to the spike in patient engagement during 2020, it is irrefutable that telehealth facilitated engagement as it was the only way to engage at the time. The years 2021 and 2022 saw the introduction of a hybrid method of care which may explain heightened engagement levels compared with 2019. The reduction in engagement from 2020 levels in these years may reflect the end of isolation, and more opportunities for alternative interaction.

Citation: Chaudhry, S., Roy, R., Mansourian, K., Weiss, A., & Breier, A. (2023). Psychosis, telehealth, and covid-19: Engagement and hospitalization pre- and peri-pandemic. Disaster Medicine and Public Health Preparedness, 17. https://doi.org/10.1017/dmp.2023.144

### [A systematic review of psychosis in social work literature](https://doi.org/10.1080/15332985.2022.2029667)

The RAISE trials highlighted the effectiveness of coordinated specialty care for psychosis. However, these publications are largely absent from the social work literature. We have reviewed nine major journals for papers related to psychotic disorders and their treatment since the RAISE trials. We found that five of the nine journals had no relevant articles, two had a single article, and the remaining journals had three and four articles, respectively. The RAISE trials were not mentioned in any of the papers. These results highlight the poor visibility of psychosis in social work. Poor visibility limits social work’s ability to provide care despite its prevalence in adjacent fields.

Citation: Chaudhry, S., Roy, R., Weiss, A., & Hansel, T. (2022). A systematic review of psychosis in social work literature. Social Work in Mental Health, 20(5), 517–529. https://doi.org/10.1080/15332985.2022.2029667

## The Becker Lab

### [Mating May Enhance Rapid Formation of Stable Pair Bonds in the Monogamous California Mouse](https://doi.org/10.1111/eth.13545)

Pair bonds are a hallmark of many monogamous species, yet in the monogamous California mouse (Peromyscus californicus) pair-bond formation is poorly understood. While pair bonds are often assumed to be present after a week of cohabitation, when they actually form in this species is debated. To characterize pair bond latency in California mice, we conducted three-chamber partner preference tests for both males and females following 1, 3, 5, or 7 days of cohabitation. Since copulation may contribute to pair-bond formation, animals were paired when females were in estrus and were assessed continuously throughout the cohabitation period for copulatory behavior. We found evidence of pair bonds after 24 h of cohabitation for both sexes with no significant changes in partner preference behaviors across cohabitation periods. Focal animals spent more time in the partner's chamber, were more affiliative toward the partner than the stranger and displayed more aggressive behavior toward the stranger. Affiliative behaviors were consistent between the sexes, while males attacked the stranger more frequently and for longer durations than females. Pairs that copulated prior to partner-preference testing spent more time in the partner's chamber and more time huddling, licking, and grooming their mate than those that did not copulate. We conclude that although copulation may not be necessary for pair-bond formation, sexual receptivity at time of pairing is important for the development of these social relationships and that copulation may serve to enhance pair bonds in California mice.

Citation: Roy, R., Hammerdahl, E., Sage, A., & Becker, E. A. (2025). Mating may enhance rapid formation of stable pair bonds in the monogamous California mouse. Ethology. https://doi.org/10.1111/eth.13545

### [Reproductive success diminished following mate loss for females but not males in a monogamous rodent](https://doi.org/10.1016/j.beproc.2021.104415)

The strictly monogamous California mouse (Peromyscus californicus) forms life-long pair bonds and mates exclusively with a single partner. While studies in the wild indicate that individuals may re-pair with a new partner following mate loss, the preponderance of this behavior and subsequent reproductive outcomes following re-pairing are understudied. To examine reproductive outcomes following re-pairing and to look for sex-specific differences following mate loss, birth records of 584 California mouse pairs from our laboratory were analyzed. Of these pairs, 59 pairs were identified as re-pairs and used for further descriptive analysis. We found that 50/59 (84.7 %) of re-paired animals gave birth, indicating that reproduction with a new mate is not only possible, but perhaps more common than previously described for this species. Additionally, we found that when re-paired, females took significantly longer to birth a subsequent litter as compared to original breeding pairs. Overall findings from the current study provide evidence for sex differences in reproductive outcomes following repairing and for greater flexibility in mating strategy for a species described as strictly monogamous.

Citation: Valentino, A., Roy, R., & Becker, E. A. (2021). Reproductive success diminished following mate loss for females but not males in a monogamous rodent. Behavioural Processes, 188, 104415. https://doi.org/10.1016/j.beproc.2021.104415

